#### Задача 1. 

Ученики одной школы все знают хотя бы по одному языку. Программа получает число школьников, а потом в цикле for собирает сведения о их языках, н-р:

    2
    English Bulgarian
    English Romanian
    
Нужно узнать, какие языки знает хотя бы один школьник и какие языки знают все школьники.

In [2]:
# your code here
n = int(input())
all_languages = set()
languages_per_student = []

for i in range(n):
    languages = input().split()
    all_languages.update(languages)
    languages_per_student.append(set(languages))

languages_everyone_knows = set.intersection(*languages_per_student)

print("Языки, которые знает хотя бы один школьник:", all_languages)
print("Языки, которые знают все школьники:", languages_everyone_knows)

Языки, которые знает хотя бы один школьник: {'Russian'}
Языки, которые знают все школьники: {'Russian'}


#### Задача 2. 

Напишите функцию, которая будет принимать строку, в которой содержится любой текст (положим, русскоязычный), и возвращать список, содержащий только слова (для удаления пунктуации можно воспользоваться punctuation из модуля string, если хочется). Если умеете пользоваться регулярками - можно использовать регулярки. 

Посчитайте частотный список слов для текста в этой строке. 

In [4]:
# your code here
import re
from collections import Counter

def get_word_frequencies(text):
    words = re.findall(r'\b\w+\b', text)
    frequencies = Counter(words)
    return frequencies

In [6]:
text = "Привет, мир! Это пример текста. Привет, мир!"
print(get_word_frequencies(text))

Counter({'Привет': 2, 'мир': 2, 'Это': 1, 'пример': 1, 'текста': 1})


#### Задача 3. 

Положим, у нас есть список со вложенными списками (глубина вложенности может быть какая угодно: это может быть список списков списков...). Напишите функцию, которая будет рекурсивно обходить все элементы в этих списках и посчитает, сколько всего встретилось уникальных элементов. Считаем, что эти элементы - целые числа (вам понадобится проверять type(x) == int). 

In [11]:
# your code here
def spiski(lst):
    unique_elements = set()

    for element in lst:
        if isinstance(element, list):
            unique_elements.update(spiski(element))
        elif isinstance(element, int):
            unique_elements.add(element)

    return unique_elements

In [12]:
lst = [1, [2, [3, [4, 5]], 6], 7, [8, 9]]
unique_elements = spiski(lst)
print(len(unique_elements))

9


#### Задача 4. 

Напишите функцию для сложения матриц.

In [13]:
# your code here
import numpy as np

def plus_matrixes(matrix1, matrix2):

    matrix1 = np.array(matrix1)
    matrix2 = np.array(matrix2)
    
    if matrix1.shape != matrix2.shape:
        raise ValueError("Матрицы должны иметь одинаковые размеры")
    
    result = matrix1 + matrix2
    
    return result

In [15]:
matrix1 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matrix2 = [[9, 8, 7], [6, 5, 4], [3, 2, 1]]

result = plus_matrixes(matrix1, matrix2)

for row in result:
    print(row)

[10 10 10]
[10 10 10]
[10 10 10]


#### Задача 5. 

Напишите функцию для умножения матриц.

In [ ]:
# your code here
import numpy as np

def multiply_matrices(matrix1, matrix2):
    
    matrix1 = np.array(matrix1)
    matrix2 = np.array(matrix2)
    
    if matrix1.shape[1] != matrix2.shape[0]:
        raise ValueError("Матрицы должны иметь одинаковые размеры")
    
    result = np.dot(matrix1, matrix2)
    
    return result

In [ ]:
matrix1 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matrix2 = [[9, 8, 7], [6, 5, 4], [3, 2, 1]]

result = mult_matrixes(matrix1, matrix2)

for row in result:
    print(row)

#### Задача 6. 

Напишите функцию, которая генерирует [матрицу сдвига](https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D1%82%D1%80%D0%B8%D1%86%D0%B0_%D1%81%D0%B4%D0%B2%D0%B8%D0%B3%D0%B0). У функции должно быть два параметра: n (размер матрицы) и bias (на сколько столбцов сдвигать).

In [16]:
# your code here
import numpy as np

def shift_matrix(n, bias):

    matrix = np.zeros((n, n))

    for i in range(n):
        matrix[:, i] = np.roll(np.arange(1, n+1), bias)

    return matrix

In [17]:
matrix = shift_matrix(4, 2)

for row in matrix:
    print(row)

[3. 3. 3. 3.]
[4. 4. 4. 4.]
[1. 1. 1. 1.]
[2. 2. 2. 2.]


#### Задача 7. 

Напишите функцию transpose(m), которая будет транспонировать матрицу.

In [19]:
# your code here
def transpose(m):

    transposed = [list(i) for i in zip(*m)]

    return transposed

In [20]:
matrix = [[1, 2, 3], [4, 5, 6]]

transposed = transpose(matrix)

for row in transposed:
    print(row)

[1, 4]
[2, 5]
[3, 6]


#### Задача 8 (\*). 

Жизнь. Напишите игру "Жизнь". Что это такое - читайте в википедии и здесь: http://www.michurin.net/online-tools/life-game.html 

Вообще говоря, это не игра в привычном понимании этого слова, а процесс. В простейшем виде достаточно раз в 0.1 секунды выводить на экран обновлённое поле (обновлять консоль можно с помощью команды os.clear('cls'), модуль os. Для macOS может немного отличаться, погуглите). Для рамочек можно использовать специальные символы для рисования рамочек (найдите в таблице unicode). Пробел - пустая клетка, живая клетка может быть обозначена, например, символом '+'. Начальное поле генерируется случайным образом, вероятность появления жизни в клетке при начальной генерации - должна быть настраиваемым параметром. Размеры поля вводит пользователь при запуске программы. Также должна быть возможность в качестве начальной популяции использовать [R-pentomino](http://www.conwaylife.com/wiki/R-pentomino).

In [ ]:
# your code here

#### Задача 9. 

Рекурсивная генерация последовательностей На вход программе задается два числа N и K. Напечатайте все последовательности длины N, на каждом месте в последовательности может стоять любое число от 1 до K, но нигде подряд не стоит двух одинаковых чисел. Программа должна напечатать все такие последовательности в лексикографическом порядке. Каждая последовательность должна быть напечатана на отдельной строке. Числа в последовательности должны разделяться пробелами.

Пример входных данных:

    4 3

Пример выходных данных:

    1 2 1 2
    1 2 1 3
    1 2 3 1
    1 2 3 2
    1 3 1 2
    1 3 1 3
    1 3 2 1
    1 3 2 3
    2 1 2 1
    2 1 2 3
    2 1 3 1
    2 1 3 2
    2 3 1 2
    2 3 1 3
    2 3 2 1
    2 3 2 3
    3 1 2 1
    3 1 2 3
    3 1 3 1
    3 1 3 2
    3 2 1 2
    3 2 1 3
    3 2 3 1
    3 2 3 2

In [ ]:
# your code here